version: "3.3"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER:root
      - MYSQL_DATABASE=tpachato
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
  spring:
    depends_on:
      - mysqldb
    build: /home/tpAchatProject
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" :"root",
        "spring.datasource.password" :"root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angular:
    image: nginx
    restart: on-failure
    container_name: angular
    ports:
     - 2011:2011
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:z
      - /var/lib/jenkins/workspace/LiaisonJenkinsDockerTest/crud-tuto-front/dist/crudtuto-Front/:/usr/share/nginx/html:z
 
volumes:
  data:

