---
- name: stopping containers
  hosts: servers
  remote_user: root
  become: true
  tasks:
    - name: Stop nexus
      command: docker stop nexus
      ignore_errors: yes
    - name: Stop sonarQube
      command: docker stop reverent_joliot
      ignore_errors: yes
    - name: Stop prometheus
      command: docker stop prometheus
      ignore_errors: yes
    - name: Stop grafana
      command: docker stop grafana
      ignore_errors: yes
